=== DBOMproject/chainsource-gateway/src/testdata/schema_tests/core/good_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "required": [
    "standardVersion",
    "documentName",
    "documentCreator",
    "documentCreatedDate",
    "assetType",
    "assetSubType",
    "assetManufacturer",
    "assetModelNumber",
    "assetDescription",
    "assetMetadata",
    "manufactureSignature"
  ],
  "additionalProperties": false,
  "properties": {
    "standardVersion": {
      "$id": "#/properties/standardVersion",
      "type": "number",
      "default": 1
    },
    "documentName": {
      "$id": "#/properties/documentName",
      "type": "string",
      "minLength": 1
    },
    "documentCreator": {
      "$id": "#/properties/documentCreator",
      "type": "string",
      "minLength": 1
    },
    "documentCreatedDate": {
      "$id": "#/properties/documentCreatedDate",
      "type": "string",
      "minLength": 1
    },
    "assetType": {
      "$id": "#/properties/assetType",
      "type": "string",
      "minLength": 1
    },
    "assetSubType": {
      "$id": "#/properties/assetSubType",
      "type": "string",
      "minLength": 1
    },
    "assetManufacturer": {
      "$id": "#/properties/assetManufacturer",
      "type": "string",
      "minLength": 1
    },
    "assetModelNumber": {
      "$id": "#/properties/assetModelNumber",
      "type": "string",
      "minLength": 1
    },
    "assetDescription": {
      "$id": "#/properties/assetDescription",
      "type": "string",
      "minLength": 1
    },
    "assetMetadata": {
      "$id": "#/properties/assetMetadata",
      "type": "object",
      "default": {}
    },
    "parentAsset":{
      "$id": "#/properties/parentAsset",
      "type": "object",
      "default": {}
    },
    "attachedChildren": {
      "$id": "#/properties/attachedChildren",
      "type": "array",
      "default": [],
      "items": {
        "$id": "#/properties/attachedChildren/items",
        "type": "object",
        "default": {},
        "required": [
          "role",
          "subRole",
          "repoID",
          "channelID",
          "assetID"
        ],
        "properties": {
          "role": {
            "$id": "#/properties/attachedChildren/items/properties/role",
            "type": "string",
            "default": ""
          },
          "subRole": {
            "$id": "#/properties/attachedChildren/items/properties/subRole",
            "type": "string",
            "default": ""
          },
          "repoID": {
            "$id": "#/properties/attachedChildren/items/properties/repoID",
            "type": "string",
            "default": ""
          },
          "channelID": {
            "$id": "#/properties/attachedChildren/items/properties/channelID",
            "type": "string",
            "default": ""
          },
          "assetID": {
            "$id": "#/properties/attachedChildren/items/properties/assetID",
            "type": "string",
            "default": ""
          }
        }
      }
    },
    "manufactureSignature": {
      "$id": "#/properties/manufactureSignature",
      "type": "string",
      "default": ""
    }
  }
}

=== DBOMproject/chainsource-gateway/src/testdata/asset_controller_tests/export/levelTwoAssetOne.json
{
  "standardVersion": 1.0,
  "documentName": "L2A1",
  "documentCreator": "A Valid Creator",
  "documentCreatedDate": "2020-07-30T06:31:58+0000",
  "assetType": "HardwareComponent",
  "assetSubType": "AValidSubType",
  "assetManufacturer": "A Valid Manufacturer",
  "assetModelNumber": "A Valid ModelNumber",
  "assetDescription": "A Valid Description",
  "parentAsset": {
    "repoID": "T1",
    "channelID": "C1",
    "assetID": "A1",
    "role": "A_Role",
    "subRole": "A_SubRole"
  },
  "assetMetadata": {
    "iAmNested": {
      "I_am_a_long_key_thats_nested": {
        "SecondLevelNestedKey": "SecondLevelNestedValue",
        "AnotherKey": "AnotherValue",
        "NestingAndValues": {
          "CombinationOfBoth": "TestValue"
        }
      },
      "YetAnotherKey": {
        "YetAnotherNestedKey": "YetAnotherNestedValue"
      }
    }
  },
  "manufactureSignature": "wsBcBAEBCAAQBQJecxBBCRDhB93OjBXccAAAlAQH/0N2HhaK6fmADG0QxK9i8xIrgncGzvii6OqPzyVtyjA7RrpgA1c5E5wN5eW8XmPaqpMvtP3RenuTlXTH2d647QnzdxYuNOKjVXGuweBMkBqnKBf8hHeH6adBTh6Jlnbt3OndMsE06BMBz59Z/X4tmKoAWXox1EPraAi9+A6BqeB5YHXDQJ6SXsW9fLKoQVECsi0MHOR+CjGcu1R1dyP5s2Vd9jcm+DLXLmxz6zTqS7h1neLMsFm4jIhxYsh5mQ49R4r6Yi76RIMK5G6LxX32BzKb9rTDSKdqRFQAv4JsoZXTPRwlM3MG/FCQWYhtvc6righlAMJOVSXTxy54TPKeXe4==SVL1"
}

=== DBOMproject/chainsource-gateway/src/testdata/asset_controller_tests/validate/assetToBeValidatedEmptySignature.json
{
  "standardVersion": 1.0,
  "documentName": "A Valid BoM",
  "documentCreator": "A Valid Creator",
  "documentCreatedDate": "2020-07-30T06:31:58+0000",
  "assetType": "HardwareComponent",
  "assetSubType": "AValidSubType",
  "assetManufacturer": "A Valid Manufacturer",
  "assetModelNumber": "A Valid ModelNumber",
  "assetDescription": "A Valid Description",
  "assetMetadata": {
    "manufactureFingerprint": "<valid-fingerprint>"
  },
  "manufactureSignature": ""
}
