=== DBOMproject/chainsource-gateway/src/testdata/schema_tests/asset/good_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "standardVersion",
    "schemaUrl",
    "created",
    "modified",
    "notarizations",
    "links",
    "signatures",
    "body",
    "id"
  ],
  "properties": {
    "standardVersion": {
      "type": "number",
      "minLength": 1
    },
    "schemaUrl": {
      "type": "string",
      "minLength": 1
    },
    "created": {
      "type": "string",
      "minLength": 1
    },
    "modified": {
      "type": "string",
      "minLength": 1
    },
    "notarizations": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "notaryId": {
            "type": "string",
            "minLength": 1
          },
          "notaryMeta": {
            "type": "object",
            "default": {}
          }
        },
        "required": ["notaryId", "notaryMeta"]
      }
    },
    "links": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "assetUri": {
            "type": "string",
            "minLength": 1
          },
          "type": {
            "type": "string",
            "minLength": 1
          },
          "comment": {
            "type": "string"
          },
          "id": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": ["assetUri", "type", "comment", "id"]
      }
    },
    "signatures": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "hashType": {
            "type": "string",
            "minLength": 1
          },
          "signType": {
            "type": "string",
            "minLength": 1
          },
          "signMeta": {
            "type": "object",
            "properties": {
              "authority": {
                "type": "string",
                "minLength": 1
              },
              "keyId": {
                "type": "string",
                "minLength": 1
              },
              "sign": {
                "type": "string",
                "minLength": 1
              }
            },
            "required": ["authority", "keyId", "sign"]
          }
        },
        "required": ["hashType", "signType", "signMeta"]
      }
    },
    "body": {
      "type": "object",
      "default": {}
    },
    "id": {
      "type": "string"
    }
  }
}

=== DBOMproject/chainsource-gateway/src/testdata/schema_tests/asset/valid.json
{
  "standardVersion": 1,
  "schemaUrl": "https://raw.githubusercontent.com/spdx/spdx-spec/development/v2.3.1/schemas/spdx-schema.json",
  "created": "2023-05-15T12:34:56Z",
  "modified": "2023-05-15T12:34:56Z",
  "notarizations": [
    {
      "notaryId": "not1",
      "notaryMeta": {}
    }
  ],
  "links": [
    {
      "assetUri": "string",
      "type": "asset",
      "comment": "example2",
      "id": "Link1"
    }
  ],
  "signatures": [
    {
      "hashType": "SHA256",
      "signType": "type1",
      "signMeta": {
        "authority": "user1",
        "keyId": "12345",
        "sign": "asdfbiuvagebvbayerfasdfbsjasdfdliufgalsi"
      }
    }
  ],
  "body": {},
  "id": "id1"
}
