=== DBOMproject/chainsource-gateway/src/testdata/schema_tests/channel/good_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "additionalProperties": false,
  "required": ["channelId", "description", "type", "notaries", "createdAt", "modifiedAt"],
  "properties": {
    "channelId": {
      "type": "string",
      "minLength": 1
    },
    "description": {
      "type": "string",
      "minLength": 1
    },
    "type": {
      "type": "string",
      "minLength": 1
    },
    "notaries": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          },
          "type": {
            "type": "string",
            "minLength": 1
          },
          "config": {
            "type": "object",
            "default": {}
          }
        },
        "required": ["id", "type", "config"]
      }
    },
    "createdAt": {
      "type": "string",
      "minLength": 1
    },
    "modifiedAt": {
      "type": "string",
      "minLength": 1
    }
  }
}

=== DBOMproject/chainsource-gateway/src/testdata/schema_tests/channel/valid.json
{
  "channelId": "channel1",
  "description": "Channel1 of Node 1 - Remote",
  "type": "TEST_CHANNEL",
  "notaries": [
      {
          "id": "ahgsduih",
          "type": "SIGNED",
          "config": {}
      }
  ],
  "createdAt": "2023-08-13T22:08:42.986Z",
  "modifiedAt": "2023-08-13T22:08:42.986Z"
}
